# Generated by Django 5.0.6 on 2024-06-19 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0002_alter_medication_dosage_alter_medication_frequency_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medication',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
