# Generated by Django 5.0.6 on 2024-06-20 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0003_alter_medication_end_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='refill_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
