# Generated by Django 5.0.6 on 2024-06-21 21:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0005_medication_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='user',
        ),
    ]
