# Generated by Django 5.0.6 on 2024-06-26 02:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0007_medication_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='taken_days',
            field=models.JSONField(default=list),
        ),
    ]
