# Generated by Django 5.0.6 on 2024-06-29 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0008_medication_taken_days'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='medication',
            name='taken_days',
        ),
    ]
