# Generated by Django 5.0.6 on 2024-06-29 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0009_remove_medication_taken_days'),
    ]

    operations = [
        migrations.AddField(
            model_name='medication',
            name='taken',
            field=models.BooleanField(default=False),
        ),
    ]
