# Generated by Django 5.0.6 on 2024-07-03 19:10

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0013_medicationlog_delete_medicationstaken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='medicationlog',
            unique_together={('user', 'medication', 'date')},
        ),
    ]
