# Generated by Django 5.0.6 on 2024-07-07 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0014_alter_medicationlog_unique_together'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccountUser',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
