# Generated by Django 5.0.6 on 2024-07-07 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medapp', '0015_accountuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AccountUser',
        ),
    ]
